# PyTorch Introduction

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [3]:
print("pytorch version :", torch.__version__)

pytorch version : 2.13.0+cpu


In [4]:
# check gpu availability
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device :", device)
if torch.cuda.is_available():
    print("gpu name: ", torch.cuda.get_device_name(0))

device : cpu


## creating tensors

In [5]:
# tensor form list
x = torch.tensor([1, 2, 3, 4])
print("x:", x)

x: tensor([1, 2, 3, 4])


In [6]:
# float tensor
y = torch.tensor([1.0, 2.4, 5.0])
print("y:", y)

y: tensor([1.0000, 2.4000, 5.0000])


In [7]:
# matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("martix:")
print(matrix)

martix:
tensor([[1, 2, 3],
        [4, 5, 6]])


## Tensor attribute

In [8]:
x = torch.rand(3, 5)
print("tensor:")
print(x)
print("shape:", x.shape)
print("data type:", x.dtype)
print("device:", x.device)

tensor:
tensor([[0.5142, 0.2623, 0.8750, 0.0338, 0.1353],
        [0.7567, 0.8652, 0.8158, 0.0152, 0.2379],
        [0.2274, 0.5588, 0.6120, 0.9994, 0.6961]])
shape: torch.Size([3, 5])
data type: torch.float32
device: cpu


## special tensor creation

In [9]:
zeros = torch.zeros(3, 4)
ones = torch.ones(2, 5)
random_uniform = torch.rand(3, 3)
random_normal = torch.randn(3, 3)
identity = torch.eye(4)
print("zeros:")
print(zeros)
print("ones:")
print(ones)
print("random_uniform:")
print(random_uniform)
print("random_normal:")
print(random_normal)
print("identity:")
print(identity)

zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
random_uniform:
tensor([[0.0658, 0.2394, 0.5813],
        [0.9149, 0.1538, 0.7081],
        [0.7838, 0.8771, 0.4086]])
random_normal:
tensor([[-0.5247,  0.2586, -0.2791],
        [-0.0865, -0.2504,  1.3708],
        [ 0.3055, -0.6236, -0.1868]])
identity:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


## tensor indexing

In [10]:
x = torch.tensor([10, 20, 30, 40, 50])
print("x:", x)
print("first element:", x[0])
print("last element:", x[-1])
print("first three elements:", x[0:3])
print("from index 2 onward", x[2:])

x: tensor([10, 20, 30, 40, 50])
first element: tensor(10)
last element: tensor(50)
first three elements: tensor([10, 20, 30])
from index 2 onward tensor([30, 40, 50])


## 2d tensor indexing

In [11]:
matrix = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("martix:")
print(matrix)
print("element at row 0 column 1", matrix[0, 1])
print("first row", matrix[0])
print("second column", matrix[:, 1])
print("top left 2x2 block:")
print(matrix[0:2, 0:2])

martix:
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
element at row 0 column 1 tensor(20)
first row tensor([10, 20, 30])
second column tensor([20, 50, 80])
top left 2x2 block:
tensor([[10, 20],
        [40, 50]])


## tensor reshaping

In [13]:
x = torch.arange(12)
print("original tensor :")
print(x)
print("original tensor shape :", x.shape)

x_reshaped = x.reshape(3, 4)
print("reshaped tensor :")
print(x_reshaped)
print("reshaped tensor shape :", x_reshaped.shape)

original tensor :
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
original tensor shape : torch.Size([12])
reshaped tensor :
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
reshaped tensor shape : torch.Size([3, 4])
