# Python Modules : NumPy
NumPy was created in 2005 by Travis Oliphant written in Python, C/C++.

NumPy or "Numerical Python"  is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [2]:
# importing NumPy
import numpy as np

# Checking NumPy Version
print(np.__version__)

2.4.6


# Why Use NumPy?
Python lists serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

# Create a NumPy array

In [3]:
arr = np.array([1, 2, 3, 4, 6])
print(arr)
print(type(arr))

[1 2 3 4 6]
<class 'numpy.ndarray'>


### To create an ndarray, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into a `darray`

In [4]:
t = (1, 2, 3, 5, 6, 5)
arr = np.array(t)
print(arr)

[1 2 3 5 6 5]


# Dimensions in Arrays

In [5]:
a = np.array(42)  # 0-D Arrays
b = np.array([1, 2, 3, 4, 5])  # 1-D Arrays
c = np.array([[1, 2, 3], [4, 5, 6]])  # 2-D Arrays
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  # 3-D Arrays

In [6]:
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# Higher Dimensional Arrays

In [7]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


# Access Array Elements

In [8]:
arr = np.array([10, 2, 3, 6])
print(arr[0])

10


In [9]:
arr = np.array([[1, 20, 39, 3, 5], [3, 5, 9, 22, 9]])
print(arr[0, 1])
print(1, 4)

20
1 4


In [10]:
# Access the third element of the second array of the first array:
arr = np.array(
    [
        [[1, 2, 3], [4, 5, 60]],
        [[7, 8, 9], [10, 11, 12]],
        [[7, 8, 9], [10, 11, 120]],
    ]
)
print(arr)
print(arr[2, 1, 2])

[[[  1   2   3]
  [  4   5  60]]

 [[  7   8   9]
  [ 10  11  12]]

 [[  7   8   9]
  [ 10  11 120]]]
120


# Negative Indexing

In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 100]])
print("Last element from 2nd dim: ", arr[1, 4])
print("Last element from 2nd dim: ", arr[1, -1])
print("Last element from 2nd dim: ", arr[-1, -1])

Last element from 2nd dim:  100
Last element from 2nd dim:  100
Last element from 2nd dim:  100


# Slicing arrays
Syntax : [start:end:step]

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [12]:
l = [10, 20, 30, 40, 50, 60, 70]
arr = np.array(l)

print(arr[1:5])

[20 30 40 50]


In [13]:
l = [10, 20, 30, 40, 50, 60, 70]
# Slice elements from index 4 to the end of the array:
print(arr[4:])
# Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[50 60 70]
[10 20 30 40]


In [14]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])  # start:end

[5 6]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])  # start:end:step
print(arr[-5:-2:2])  # start:end:step

[2 4]
[3 5]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])  # start:end:step

[1 3 5 7]


#  Slicing 2-D Arrays

In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [18]:
# From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])  # row, col

[3 8]


In [19]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Data Types
Below is a list of all data types in NumPy and the characters used to represent them.
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

**The NumPy array object has a property called `dtype` that returns the data type of the array**


In [20]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64


In [28]:
# Create an array with data type 4 bytes (32 bit) integer:
arr = np.array([1, 2, 3, 4], dtype="i4")  #  change to : dtype='i4'
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the `astype()` method.

The `astype()` function creates a copy of the array, and allows you to specify the data type as a parameter.

In [29]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.1])
# arr=int(arr) # wrong
# print(arr)

newarr = arr.astype(bool)
newarr = arr.astype("i")  # a string, like 'f' for float, 'i' for integer etc
newarr = arr.astype("int")  # float for float and int for integer.
arr = np.array(newarr, dtype="i8")  #  change to : dtype='i8'

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


# NumPy Array Shape

In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [31]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("shape of array :", arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr1 = arr.reshape(-1)
newarr2 = arr.flatten()
print(newarr1)
print(newarr2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# numpy.arange() in Python
The `arange([start],[stop],[step],[dtype])` : Returns an array with evenly spaced elements as per the interval.

In [38]:
print("A\n", np.arange(4).reshape(2, 2), "\n")
print("B\n", np.arange(4, 10), "\n")
print("C\n", np.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

B
 [4 5 6 7 8 9] 

C
 [ 4  7 10 13 16 19] 



In [39]:
# Printing all numbers from 1 to 2 in steps of 0.1
print(np.arange(1, 2, 0.1))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


# NumPy Array Iterating

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


# NumPy Array Copy vs View
The copy creates a new array, and the view is just a view of the original array.

In [42]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [43]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [44]:
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Joining NumPy Array

In [45]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [48]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1.shape)
print(arr2.shape, "\n")
arr = np.concatenate((arr1, arr2))
print(arr.shape, "\n")
print(arr)

(2, 2)
(2, 2) 

(4, 2) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# Join two 2-D arrays along column (axis=0)
arr = np.concatenate((arr1, arr2))
print(arr.shape)
print(arr)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
# Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr.shape)
print(arr)

(2, 4)
[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions

In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# NumPy provides a helper function: hstack() to stack along rows.
arr = np.hstack((arr1, arr2))
print(arr)
print()
# NumPy provides a helper function: vstack()  to stack along columns.
arr = np.vstack((arr1, arr2))
print(arr)
print()
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr = np.dstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


# Searching Arrays
To search an array, use the `where()` method.

In [57]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


# NumPy Sorting Arrays

In [58]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [59]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filter

In [60]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]
